apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod2
spec:
  restartPolicy: OnFailure
  tolerations:
    - key: "nvidia.com/gpu"  # type=specialnode 확인
      effect: "NoSchedule"
  containers:
    - name: cuda-container
      image: nvidia/cuda:10.2-base
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU